name: Markdown Tutorial
url: "localhost:markdowntutorial.herokuapp.com"
permalink: pretty
exclude: [
  # Folders
  "bin",
  "script",
  "vendor",
  "spec",

  # Files
  "*.sublime*",
  "Gemfile*",
  "CONTRIBUTING.md",
  "README.md",
  "Rakefile",
  "bower.json",
  "config.ru"
]
baseurl: localhost:markdowntutorial.herokuapp.com
gems:
  - jekyll-coffeescript
